import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Document from 'next/document';
import { useEffect } from 'react';
import PageChunk from '../components/page_chunk';
import Nav from '../components/nav';
import AboutMe from '../components/about_me';
import Experience from '../components/experience';

export default function Home() {
  const skills = [["Ruby/Rails", "ruby"], ["Javascript", "js"], ["HTML", "html"], ["CSS", "css"]]
  return (
    <div className={styles.container}>
      <Head>
        <title>Colin Alexander / Software</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PageChunk flex='true'>
          <div>
            <Image src="/cloud.svg" alt="Cloud Logo" width={640} height={360} />
          </div>

          <h1 className={styles.name}>colin alexander</h1>
          <h4 className={styles.job_title}>fullstack engineer <span>/</span> devOps</h4>
          <h5 className={styles.sub_name}>forever curious, always learning</h5>

          <div className={styles.name}>
            <ul className={styles.short_skills}>
              {skills.map((skill) => (
                <li key={skill[1]}>
                  <span id={skill[1]} className="badge bg-secondary">{skill[0]}</span>
                </li>
              ))}
            </ul>
          </div>
        </PageChunk>
        <Nav/>
        <PageChunk>
          <AboutMe/>
          <Experience/>
        </PageChunk>
      </main>
    </div>
  );
}
